<a href="https://colab.research.google.com/github/aiswaryavijayan2004/Numpy-Pandas-Assesment-/blob/main/NumPy_and_Pandas_Aiswarya_Vijayan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [8]:
import numpy as np
import pandas as pd

#Question 1

Q1. NumPy Array Creation

In [ ]:
array=np.array([10,20,30,40,50])
print(array)
print(array.shape)
print(array.dtype)

[10 20 30 40 50]
(5,)
int64

#Q2. NumPy Array Operations

In [ ]:
import numpy as np
arr = np.array([5, 10, 15, 20, 25])
arr = np.array([5, 10, 15, 20, 25])

print( arr + 5)
print( arr * 2)

[10 15 20 25 30]
[10 20 30 40 50]

Q3. NumPy Statistical Operations

In [ ]:

arr = np.array([12, 15, 18, 20, 25, 30])

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Standard deviation:", np.std(arr))

Mean: 20.0
Median: 19.0
Minimum: 12
Maximum: 30
Standard deviation: 6.027713773341708

Q4. NumPy Filtering

In [ ]:
arr = np.array([10, 25, 30, 45, 50, 65, 70])

result = arr[arr > 40]

print(result)

[45 50 65 70]

Q5. Create a Pandas DataFrame

In [ ]:
df = pd.DataFrame({
    'Name': ['Anu', 'Rahul', 'Meera', 'Arun'],
    'Age': [21, 22, 20, 23],
    'Score': [85, 72, 91, 68]
})

print(df)

    Name  Age  Score
0    Anu   21     85
1  Rahul   22     72
2  Meera   20     91
3   Arun   23     68

In [ ]:
#1
print(df[['Name', 'Score']])

    Name  Score
0    Anu     85
1  Rahul     72
2  Meera     91
3   Arun     68

In [ ]:
#2
print(df[df['Name'] == 'Meera'])

    Name  Age  Score
2  Meera   20     91

Q7. DataFrame Filtering

In [ ]:
result = df[df['Score'] > 75]

print(result)

    Name  Age  Score
0    Anu   21     85
2  Meera   20     91

Q8. DataFrame Inspection

In [ ]:
print("Shape:", df.shape)

print("Column names:")
print(df.columns)

print("Data types:")
print(df.dtypes)

print("Statistical summary:")
print(df.describe())

Shape: (4, 3)
Column names:
Index(['Name', 'Age', 'Score'], dtype='object')
Data types:
Name     object
Age       int64
Score     int64
dtype: object
Statistical summary:
             Age      Score
count   4.000000   4.000000
mean   21.500000  79.000000
std     1.290994  10.801234
min    20.000000  68.000000
25%    20.750000  71.000000
50%    21.500000  78.500000
75%    22.250000  86.500000
max    23.000000  91.000000

Q9. Sorting a DataFrame

In [ ]:
result = df.sort_values(by='Score', ascending=False)

print(result)

    Name  Age  Score
2  Meera   20     91
0    Anu   21     85
1  Rahul   22     72
3   Arun   23     68

Q10. Handling Missing Values

In [ ]:
df = pd.DataFrame({
'Name': ['A', 'B', 'C', 'D'],
'Age': [21, np.nan, 23, 22],
'Score': [80, 75, np.nan, 90]
})

In [ ]:

df = pd.DataFrame({
    'Name': ['A', 'B', 'C', 'D'],
    'Age': [21, np.nan, 23, 22],
    'Score': [80, 75, np.nan, 90]
})

# 1.
print(df.isnull())

# 2.
df['Age'] = df['Age'].fillna(df['Age'].mean())

# 3.
df['Score'] = df['Score'].fillna(df['Score'].mean())

print(df)

    Name    Age  Score
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
  Name   Age      Score
0    A  21.0  80.000000
1    B  22.0  75.000000
2    C  23.0  81.666667
3    D  22.0  90.000000

 #SECTION B

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/DSAB13/NumPy and Pandas Assesment/student_performance.csv')

Q11. Data Loading and Exploration

In [ ]:
#1
df.head()

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9

In [ ]:
#2
df.tail()

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6

In [ ]:
#3
df.shape

(80, 11)

In [ ]:
#4
df.columns

Index(['Student_ID', 'Name', 'Gender', 'Department', 'Age', 'Attendance',
       'Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score',
       'Final_Score'],
      dtype='object')

In [ ]:
#5
df.dtypes

Student_ID       object
Name             object
Gender           object
Department       object
Age             float64
Attendance      float64
Python_Score    float64
SQL_Score       float64
Pandas_Score    float64
NumPy_Score     float64
Final_Score     float64
dtype: object

In [ ]:
#6
df.describe()

,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
count,77.000000,77.000000,78.000000,80.000000,78.000000,78.000000,78.000000
mean,22.012987,81.672727,72.821795,70.445000,70.365385,68.574359,70.696154
std,2.155126,10.054204,16.722103,14.630417,15.814294,16.417242,14.053871
min,19.000000,56.300000,39.500000,38.300000,25.000000,25.000000,40.600000
25%,20.000000,75.500000,64.525000,60.650000,61.800000,57.175000,60.450000
50%,22.000000,81.100000,72.000000,69.300000,70.000000,70.700000,70.950000
75%,24.000000,86.400000,86.525000,81.150000,82.575000,80.650000,82.275000
max,25.000000,100.000000,100.000000,100.000000,100.000000,100.000000,97.000000

Q12. Filtering and Sorting

In [ ]:
#1
result = df[df['Final_Score'] > 75]
print(result)

   Student_ID            Name  Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
4     STU1005       Asha Nair  Female      Data Science  22.0        71.4
6     STU1007     Akhil Varma    Male       Electronics  22.0        73.2
7     STU1008     Akhil Varma    Male  Computer Science  20.0        81.1
8     STU1009      Diya Menon    Male      Data Science  25.0        64.4
10    STU1011        Diya Das  Female      Data Science  20.0       100.0
11    STU1012      Arun Reddy    Male       Electronics  20.0        69.1
16    STU1017    Rahul Thomas  Female      Data Science  25.0        78.3
17    STU1018      Priya Nair    Male      Data Science  19.0        85.4
23    STU1024  Fathima Joseph  Female          Commerce  23.0        78.2
24    STU1025     Kiran Varma  Female       Electronics  21.0        80.7
27    STU1028     Nikhil Nair  Female      Data Science  24.0        79.3
30    STU1031      Amal Varma  Female  Computer Science  19.0        86.7
33    STU1034        Amal Das    Male  Computer Science  19.0        85.5
35    STU1036      Maya Menon  Female       Electronics  19.0        82.0
37    STU1038    Kiran Pillai  Female       Electronics  25.0        85.2
39    STU1040    Rohan Sharma  Female  Computer Science  21.0       100.0
40    STU1041     Amal Pillai  Female  Computer Science  25.0        97.7
41    STU1042     Arun Joseph  Female  Computer Science  21.0        85.9
43    STU1044       Rahul Das  Female  Computer Science  22.0        70.9
47    STU1048     Priya Kumar    Male      Data Science  25.0        64.6
48    STU1049     Asha Sharma    Male      Data Science  22.0        91.3
51    STU1052      Gokul Nair  Female          Commerce  25.0        77.3
55    STU1056     Vivek Varma    Male      Data Science  22.0        81.0
56    STU1057    Rohan Pillai  Female          Commerce  20.0        79.5
57    STU1058     Diya Thomas  Female  Computer Science  23.0        83.5
58    STU1059       Anu Menon    Male       Electronics  24.0        96.7
59    STU1060      Asha Menon    Male      Data Science  19.0        56.3
61    STU1062    Kiran Pillai  Female  Computer Science  19.0        83.8
64    STU1065    Rohan Sharma    Male  Computer Science  19.0        64.4
67    STU1068        Maya Das  Female  Computer Science  23.0        66.7
73    STU1074       Anu Kumar  Female  Computer Science  22.0        95.0
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0           89.4       86.3          81.9         76.7         82.7
4           90.1       82.9          72.4         87.7         81.9
6           81.7       82.2          81.5         64.2         77.0
7           72.1       80.4          72.9         73.5         79.2
8           94.8       86.0          87.7        100.0         83.0
10         100.0       93.2         100.0         89.3         91.9
11          80.4       78.0          88.9         77.1         86.9
16          80.8       99.4          77.2        100.0         91.1
17          62.6       81.6          79.6         75.5         75.1
23          87.7       71.0          88.5         74.8         83.7
24          87.5       67.1          84.5         96.1         77.3
27          70.3       82.0          64.4         72.8         77.1
30          86.9       64.3         100.0         89.2         85.5
33          94.4       81.6          71.3         81.5         84.3
35          95.3       93.4         100.0         62.5         84.2
37          87.8       78.3          85.5         82.7         82.4
39          68.9       79.8          66.1         66.4         78.5
40          94.3       91.0          73.1         91.2         94.5
41          71.2       76.1          70.8          NaN         77.9
43          68.0       67.3          83.6         76.7         77.3
47          80.6       67.0          71.2         80.2         77.3
48          88.9       95.0           NaN         94.5         97.0
51          80.4       85.3          96.7         83.5         79.3
55          87.0       95.1          88.4         75.7         93.3
56          72.1       66.9          61.8         72.3         75.2
57          93.1       78.8          91.6         83.8         92.3
58          99.7       77.1          68.9         89.7         84.9
59         100.0       85.0          87.4         57.4         87.9
61         100.0      100.0          89.4         91.4         96.0
64          96.5       69.3          86.7         80.7         83.5
67          83.4       79.6          89.3         83.6         83.7
73          95.3       67.7          92.4         81.4         83.4
77          70.4       75.7          98.2         76.7         75.2
79          80.5       94.3          58.6         74.9         78.6

In [ ]:
#2
result2 = df[df['Attendance'] < 75]

print(result2)

   Student_ID            Name    Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma      Male  Computer Science  25.0        74.7
2     STU1003  Fathima Joseph    Female       Electronics  21.0        60.5
4     STU1005       Asha Nair    Female      Data Science  22.0        71.4
6     STU1007     Akhil Varma      Male       Electronics  22.0        73.2
8     STU1009      Diya Menon      Male      Data Science  25.0        64.4
9     STU1010    Gokul Pillai    Female  Computer Science  19.0        67.3
11    STU1012      Arun Reddy      Male       Electronics  20.0        69.1
15    STU1016    Nikhil Kumar    Female  Computer Science   NaN        70.3
19    STU1020    Vivek Sharma    Female          Commerce  22.0        72.1
25    STU1026      Maya Menon      Male       Electronics  20.0        68.3
36    STU1037    Nikhil Menon      Male       Electronics  22.0        74.8
42    STU1043     Sneha Varma   female       Data Science  19.0        74.4
43    STU1044       Rahul Das    Female  Computer Science  22.0        70.9
47    STU1048     Priya Kumar      Male      Data Science  25.0        64.6
50    STU1051     Gokul Menon      Male      Data Science  25.0        70.9
59    STU1060      Asha Menon      Male      Data Science  19.0        56.3
64    STU1065    Rohan Sharma      Male  Computer Science  19.0        64.4
67    STU1068        Maya Das    Female  Computer Science  23.0        66.7
71    STU1072    Vivek Pillai      Male          Commerce  24.0        71.5

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0           89.4       86.3          81.9         76.7         82.7
2           79.9       80.4          65.3         68.0         67.1
4           90.1       82.9          72.4         87.7         81.9
6           81.7       82.2          81.5         64.2         77.0
8           94.8       86.0          87.7        100.0         83.0
9           79.6       85.0          74.1         80.5         73.8
11          80.4       78.0          88.9         77.1         86.9
15          55.9       69.3          67.1         58.4         58.2
19          65.8       60.9          49.8         44.8         54.6
25          91.7       64.5          83.5         73.7         69.4
36          69.5       60.7          64.6         81.6         69.1
42          71.8       79.1          69.8         95.9          NaN
43          68.0       67.3          83.6         76.7         77.3
47          80.6       67.0          71.2         80.2         77.3
50          68.6       81.0          64.0         63.0         70.5
59         100.0       85.0          87.4         57.4         87.9
64          96.5       69.3          86.7         80.7         83.5
67          83.4       79.6          89.3         83.6         83.7
71          59.0       58.2          56.3         48.9         56.6

In [ ]:
#3
result3 = df[
    (df['Department'] == 'Data Science') &
    (df['Final_Score'] > 80)
]

print(result3)

   Student_ID          Name  Gender    Department   Age  Attendance  \
4     STU1005     Asha Nair  Female  Data Science  22.0        71.4
8     STU1009    Diya Menon    Male  Data Science  25.0        64.4
10    STU1011      Diya Das  Female  Data Science  20.0       100.0
16    STU1017  Rahul Thomas  Female  Data Science  25.0        78.3
48    STU1049   Asha Sharma    Male  Data Science  22.0        91.3
55    STU1056   Vivek Varma    Male  Data Science  22.0        81.0
59    STU1060    Asha Menon    Male  Data Science  19.0        56.3

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
4           90.1       82.9          72.4         87.7         81.9
8           94.8       86.0          87.7        100.0         83.0
10         100.0       93.2         100.0         89.3         91.9
16          80.8       99.4          77.2        100.0         91.1
48          88.9       95.0           NaN         94.5         97.0
55          87.0       95.1          88.4         75.7         93.3
59         100.0       85.0          87.4         57.4         87.9

In [ ]:
#4
result4 = df.sort_values(
    by='Final_Score',
    ascending=False
)

print(result4)

   Student_ID           Name    Gender        Department   Age  Attendance  \
48    STU1049    Asha Sharma      Male      Data Science  22.0        91.3
61    STU1062   Kiran Pillai    Female  Computer Science  19.0        83.8
40    STU1041    Amal Pillai    Female  Computer Science  25.0        97.7
55    STU1056    Vivek Varma      Male      Data Science  22.0        81.0
57    STU1058    Diya Thomas    Female  Computer Science  23.0        83.5
..        ...            ...       ...               ...   ...         ...
34    STU1035   Rahul Pillai    Female      Data Science  22.0        82.5
76    STU1077     Amal Kumar      Male      Data Science   NaN        93.8
26    STU1027  Aditya Pillai    Female  Computer Science  25.0        79.6
42    STU1043    Sneha Varma   female       Data Science  19.0        74.4
53    STU1054    Maya Sharma      Male      Data Science  19.0        82.5

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
48          88.9       95.0           NaN         94.5         97.0
61         100.0      100.0          89.4         91.4         96.0
40          94.3       91.0          73.1         91.2         94.5
55          87.0       95.1          88.4         75.7         93.3
57          93.1       78.8          91.6         83.8         92.3
..           ...        ...           ...          ...          ...
34          41.4       44.4          53.8         43.2         44.2
76          45.8       43.4          58.1         38.8         43.5
26          44.0       52.5          25.0         25.0         40.6
42          71.8       79.1          69.8         95.9          NaN
53          59.7       60.5          65.8         73.3          NaN

[80 rows x 11 columns]

Q13. Feature Creation

In [ ]:
df['Average_Technical_Score'] = (
    df['Python_Score'] +
    df['SQL_Score'] +
    df['Pandas_Score'] +
    df['NumPy_Score']
) / 4

conditions = [
    df['Average_Technical_Score'] >= 90,
    df['Average_Technical_Score'] >= 75,
    df['Average_Technical_Score'] >= 60
]

choices = [
    'Excellent',
    'Good',
    'Average'
]

df['Performance'] = np.select(
    conditions,
    choices,
    default='Needs Improvement'
)

In [ ]:
print(df)

   Student_ID            Name  Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
1     STU1002    Kiran Pillai    Male  Computer Science  24.0        75.5
2     STU1003  Fathima Joseph  Female       Electronics  21.0        60.5
3     STU1004    Rahul Sharma  Female      Data Science  25.0        80.4
4     STU1005       Asha Nair  Female      Data Science  22.0        71.4
..        ...             ...     ...               ...   ...         ...
75    STU1076     Priya Kumar  Female  Computer Science  24.0        99.3
76    STU1077      Amal Kumar    Male      Data Science   NaN        93.8
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
78    STU1079    Meera Thomas    Male       Electronics  23.0        99.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score  \
0           89.4       86.3          81.9         76.7         82.7
1           70.3       63.1          65.1         62.3         60.3
2           79.9       80.4          65.3         68.0         67.1
3           65.8       50.7          52.6         48.8         57.2
4           90.1       82.9          72.4         87.7         81.9
..           ...        ...           ...          ...          ...
75          46.9       57.6          29.5         57.1         47.2
76          45.8       43.4          58.1         38.8         43.5
77          70.4       75.7          98.2         76.7         75.2
78          64.6       66.5          61.8         52.5         63.4
79          80.5       94.3          58.6         74.9         78.6

    Average_Technical_Score        Performance
0                    83.575               Good
1                    65.200            Average
2                    73.400            Average
3                    54.475  Needs Improvement
4                    83.275               Good
..                      ...                ...
75                   47.775  Needs Improvement
76                   46.525  Needs Improvement
77                   80.250               Good
78                   61.350            Average
79                   77.075               Good

[80 rows x 13 columns]

#Q14.   GroupBy Analysis

In [ ]:
# Q14. GroupBy Analysis

department_analysis = df.groupby('Department').agg(
    Number_of_Students=('Student_ID', 'count'),
    Average_Final_Score=('Final_Score', 'mean'),
    Maximum_Final_Score=('Final_Score', 'max'),
    Minimum_Final_Score=('Final_Score', 'min')
)

# Sort by Average Final Score in descending order
department_analysis = department_analysis.sort_values(
    by='Average_Final_Score',
    ascending=False
)

print(department_analysis)

                  Number_of_Students  Average_Final_Score  \
Department
Electronics                       13            72.846154
Computer Science                  29            71.479310
Data Science                      27            71.324000
Commerce                           8            67.825000
data science                       1            66.900000
 Data Science                      1            55.100000
Computer science                   1            46.700000

                  Maximum_Final_Score  Minimum_Final_Score
Department
Electronics                      86.9                 51.2
Computer Science                 96.0                 40.6
Data Science                     97.0                 43.5
Commerce                         83.7                 54.6
data science                     66.9                 66.9
 Data Science                    55.1                 55.1
Computer science                 46.7                 46.7

#Q15. NumPy and Pandas Integration

In [ ]:
# Q15. NumPy and Pandas Integration

#1
scores = df['Final_Score'].dropna().to_numpy()

#2
mean_score = np.mean(scores)
#3
median_score = np.median(scores)
#4
std_score = np.std(scores)
#5
percentile_25 = np.percentile(scores, 25)
#6
percentile_75 = np.percentile(scores, 75)

print("Mean:", mean_score)
print("Median:", median_score)
print("Standard Deviation:", std_score)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

# 7
above_mean = df[df['Final_Score'] > mean_score]

print("\nStudents with Final_Score above overall mean:")
print(above_mean)

Mean: 70.69615384615383
Median: 70.95
Standard Deviation: 13.96349124578818
25th Percentile: 60.449999999999996
75th Percentile: 82.275

Students with Final_Score above overall mean:
   Student_ID            Name  Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
4     STU1005       Asha Nair  Female      Data Science  22.0        71.4
6     STU1007     Akhil Varma    Male       Electronics  22.0        73.2
7     STU1008     Akhil Varma    Male  Computer Science  20.0        81.1
8     STU1009      Diya Menon    Male      Data Science  25.0        64.4
9     STU1010    Gokul Pillai  Female  Computer Science  19.0        67.3
10    STU1011        Diya Das  Female      Data Science  20.0       100.0
11    STU1012      Arun Reddy    Male       Electronics  20.0        69.1
16    STU1017    Rahul Thomas  Female      Data Science  25.0        78.3
17    STU1018      Priya Nair    Male      Data Science  19.0        85.4
20    STU1021      Arun Varma  Female          Commerce  25.0        79.5
23    STU1024  Fathima Joseph  Female          Commerce  23.0        78.2
24    STU1025     Kiran Varma  Female       Electronics  21.0        80.7
27    STU1028     Nikhil Nair  Female      Data Science  24.0        79.3
30    STU1031      Amal Varma  Female  Computer Science  19.0        86.7
33    STU1034        Amal Das    Male  Computer Science  19.0        85.5
35    STU1036      Maya Menon  Female       Electronics  19.0        82.0
37    STU1038    Kiran Pillai  Female       Electronics  25.0        85.2
39    STU1040    Rohan Sharma  Female  Computer Science  21.0       100.0
40    STU1041     Amal Pillai  Female  Computer Science  25.0        97.7
41    STU1042     Arun Joseph  Female  Computer Science  21.0        85.9
43    STU1044       Rahul Das  Female  Computer Science  22.0        70.9
46    STU1047       Gokul Das    Male      Data Science  21.0         NaN
47    STU1048     Priya Kumar    Male      Data Science  25.0        64.6
48    STU1049     Asha Sharma    Male      Data Science  22.0        91.3
51    STU1052      Gokul Nair  Female          Commerce  25.0        77.3
52    STU1053      Maya Varma    Male  Computer Science  22.0        84.6
55    STU1056     Vivek Varma    Male      Data Science  22.0        81.0
56    STU1057    Rohan Pillai  Female          Commerce  20.0        79.5
57    STU1058     Diya Thomas  Female  Computer Science  23.0        83.5
58    STU1059       Anu Menon    Male       Electronics  24.0        96.7
59    STU1060      Asha Menon    Male      Data Science  19.0        56.3
60    STU1061  Fathima Sharma    Male  Computer Science  24.0        79.6
61    STU1062    Kiran Pillai  Female  Computer Science  19.0        83.8
64    STU1065    Rohan Sharma    Male  Computer Science  19.0        64.4
66    STU1067    Rahul Thomas    Male      Data Science   NaN        99.3
67    STU1068        Maya Das  Female  Computer Science  23.0        66.7
72    STU1073   Swathi Joseph    Male      Data Science  22.0        78.7
73    STU1074       Anu Kumar  Female  Computer Science  22.0        95.0
74    STU1075      Gokul Nair  Female      Data Science  23.0        87.8
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score  \
0           89.4       86.3          81.9         76.7         82.7
4           90.1       82.9          72.4         87.7         81.9
6           81.7       82.2          81.5         64.2         77.0
7           72.1       80.4          72.9         73.5         79.2
8           94.8       86.0          87.7        100.0         83.0
9           79.6       85.0          74.1         80.5         73.8
10         100.0       93.2         100.0         89.3         91.9
11          80.4       78.0          88.9         77.1         86.9
16          80.8       99.4          77.2        100.0         91.1
17          62.6       81.6          79.6         75.5         75.1
20           NaN       67.6          74.3         75.3         73.2
23          87.7       71.0          88.5         74.8         83.7
24          87.5       67.1          84.5         96.1         77.3
27          70.3       82.0          64.4         72.8         77.1
30          86.9       64.3         100.0         89.2         85.5
33          94.4       81.6          71.3         81.5         84.3
35          95.3       93.4         100.0         62.5         84.2
37          87.8       78.3          85.5         82.7         82.4
39          68.9       79.8          66.1         66.4         78.5
40          94.3       91.0          73.1         91.2         94.5
41          71.2       76.1          70.8          NaN         77.9
43          68.0       67.3          83.6         76.7         77.3
46          69.5       59.3          75.2         75.2         74.8
47          80.6       67.0          71.2         80.2         77.3
48          88.9       95.0           NaN         94.5         97.0
51          80.4       85.3          96.7         83.5         79.3
52          71.9       73.4          70.0         67.2         71.0
55          87.0       95.1          88.4         75.7         93.3
56          72.1       66.9          61.8         72.3         75.2
57          93.1       78.8          91.6         83.8         92.3
58          99.7       77.1          68.9         89.7         84.9
59         100.0       85.0          87.4         57.4         87.9
60          80.8       63.1          71.1         67.9         70.8
61         100.0      100.0          89.4         91.4         96.0
64          96.5       69.3          86.7         80.7         83.5
66           NaN       56.2          69.0         81.5         70.7
67          83.4       79.6          89.3         83.6         83.7
72          76.4       77.5          73.6         65.6         73.5
73          95.3       67.7          92.4         81.4         83.4
74          85.4       80.0          65.2         70.4         70.9
77          70.4       75.7          98.2         76.7         75.2
79          80.5       94.3          58.6         74.9         78.6

    Average_Technical_Score        Performance
0                    83.575               Good
4                    83.275               Good
6                    77.400               Good
7                    74.725            Average
8                    92.125          Excellent
9                    79.800               Good
10                   95.625          Excellent
11                   81.100               Good
16                   89.350               Good
17                   74.825            Average
20                      NaN  Needs Improvement
23                   80.500               Good
24                   83.800               Good
27                   72.375            Average
30                   85.100               Good
33                   82.200               Good
35                   87.800               Good
37                   83.575               Good
39                   70.300            Average
40                   87.400               Good
41                      NaN  Needs Improvement
43                   73.900            Average
46                   69.800            Average
47                   74.750            Average
48                      NaN  Needs Improvement
51                   86.475               Good
52                   70.625            Average
55                   86.550               Good
56                   68.275            Average
57                   86.825               Good
58                   83.850               Good
59                   82.450               Good
60                   70.725            Average
61                   95.200          Excellent
64                   83.300               Good
66                      NaN  Needs Improvement
67                   83.975               Good
72                   73.275            Average
73                   84.200               Good
74                   75.250               Good
77                   80.250               Good
79                   77.075               Good

Q16.Studene Performance Analysis

A .   Data Cleanng

In [ ]:

print("Missing values:")
print(df.isnull().sum())

num_cols = ['Age', 'Attendance', 'Python_Score', 'SQL_Score',
            'Pandas_Score', 'NumPy_Score', 'Final_Score']

df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

# B. Feature Engineering
df['Average_Score'] = (
    df['Python_Score'] +
    df['SQL_Score'] +
    df['Pandas_Score'] +
    df['NumPy_Score']
) / 4

df['Pass_Status'] = np.where(
    df['Average_Score'] >= 50,
    'Pass',
    'Fail'
)

# C. Analysis

# 1. Top 5 students
print("Top 5 Students:")
print(df.sort_values('Average_Score', ascending=False).head(5))

# 2. Department having highest average score
department_avg = df.groupby('Department')['Average_Score'].mean()
print("\nDepartment with highest average score:")
print(department_avg.idxmax())

# 3. Average attendance by department
print("\nAverage Attendance by Department:")
print(df.groupby('Department')['Attendance'].mean())

# 4. Number of students passed and failed
print("\nPass and Fail Count:")
print(df['Pass_Status'].value_counts())

# D. Summary
summary = df.groupby('Department').agg(
    Total_Students=('Student_ID', 'count'),
    Average_Score=('Average_Score', 'mean'),
    Average_Attendance=('Attendance', 'mean'),
    Pass_Count=('Pass_Status', lambda x: (x == 'Pass').sum()),
    Fail_Count=('Pass_Status', lambda x: (x == 'Fail').sum())
)

print("\nSummary:")
print(summary)

Missing values:
Student_ID                 0
Name                       0
Gender                     0
Department                 0
Age                        3
Attendance                 3
Python_Score               2
SQL_Score                  0
Pandas_Score               2
NumPy_Score                2
Final_Score                2
Average_Technical_Score    6
Performance                0
Average_Score              6
Pass_Status                0
dtype: int64
Top 5 Students:
   Student_ID          Name  Gender        Department   Age  Attendance  \
10    STU1011      Diya Das  Female      Data Science  20.0       100.0
61    STU1062  Kiran Pillai  Female  Computer Science  19.0        83.8
8     STU1009    Diya Menon    Male      Data Science  25.0        64.4
16    STU1017  Rahul Thomas  Female      Data Science  25.0        78.3
35    STU1036    Maya Menon  Female       Electronics  19.0        82.0

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score  \
10         100.0       93.2         100.0         89.3         91.9
61         100.0      100.0          89.4         91.4         96.0
8           94.8       86.0          87.7        100.0         83.0
16          80.8       99.4          77.2        100.0         91.1
35          95.3       93.4         100.0         62.5         84.2

    Average_Technical_Score Performance  Average_Score Pass_Status
10                   95.625   Excellent         95.625        Pass
61                   95.200   Excellent         95.200        Pass
8                    92.125   Excellent         92.125        Pass
16                   89.350        Good         89.350        Pass
35                   87.800        Good         87.800        Pass

Department with highest average score:
Electronics

Average Attendance by Department:
Department
 Data Science       76.700000
Commerce            77.437500
Computer Science    82.768025
Computer science    92.100000
Data Science        82.076768
Electronics         80.576923
data science        81.672727
Name: Attendance, dtype: float64

Pass and Fail Count:
Pass_Status
Pass    72
Fail     8
Name: count, dtype: int64

Summary:
                  Total_Students  Average_Score  Average_Attendance  \
Department
 Data Science                  1      59.200000           76.700000
Commerce                       8      68.806931           77.437500
Computer Science              29      70.515296           82.768025
Computer science               1      53.843590           92.100000
Data Science                  27      70.671783           82.076768
Electronics                   13      74.063462           80.576923
data science                   1      64.725000           81.672727

                  Pass_Count  Fail_Count
Department
 Data Science              1           0
Commerce                   8           0
Computer Science          24           5
Computer science           1           0
Data Science              24           3
Electronics               13           0
data science               1           0

#Q18. Advanced Employee Analysis

In [11]:


import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/DSAB13/NumPy and Pandas Assesment/employee.csv')

df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')
df['Experience'] = pd.to_numeric(df['Experience'], errors='coerce')

#A.
salary = df['Salary'].dropna().values
perf = df['Performance_Score'].dropna().values

print("Mean Salary:", salary.mean())
print("Median Salary:", np.median(salary))
print("Std Salary:", salary.std())
print("Mean Performance:", perf.mean())

#B.
filtered = df[(df['Experience'] > 3) & (df['Performance_Score'] >= 80)]
print(filtered)
#C.
dept_summary = df.groupby('Department').agg(
    Average_Salary=('Salary', 'mean'),
    Average_Performance=('Performance_Score', 'mean'),
    Total_Projects=('Projects_Completed', 'sum'),
    Employee_Count=('Employee_ID', 'count')
)
print(dept_summary)
print("Highest Performance Dept:", dept_summary['Average_Performance'].idxmax())

#D.
flagged = df[(df['Salary'] > salary.mean()) & (df['Performance_Score'] < perf.mean())]
print(flagged[['Employee_ID', 'Department', 'Salary', 'Performance_Score']])

Mean Salary: 60809.281690140844
Median Salary: 61196.0
Std Salary: 18154.72754492641
Mean Performance: 71.01369863013699
   Employee_ID            Department  Experience   Salary  Performance_Score  \
1      EMP2002  Software Development         8.7  78243.0               85.6
6      EMP2007                    HR         4.6  51328.0               91.0
17     EMP2018  Software development         5.6  79595.0               83.0
22     EMP2023        Data Analytics         5.7  83674.0               81.0
25     EMP2026      Data Engineering         5.8  45336.0               88.0
26     EMP2027  Software Development         8.1  74816.0               84.3
30     EMP2031  Software Development         6.9  60930.0               94.4
31     EMP2032            IT Support         4.7  65566.0               85.7
45     EMP2046  Software Development         3.4  51056.0               92.8
48     EMP2049      Data Engineering         4.7  43341.0               82.2
49     EMP2050  Software Development         4.9  68620.0               90.9
57     EMP2058                    HR         5.3  68152.0               81.1
58     EMP2059      Data Engineering         3.8  52079.0               84.1
62     EMP2063  Software Development         7.0  74892.0               88.0
65     EMP2066  Software Development         5.9  82567.0               81.1
69     EMP2070            IT Support         3.1  60755.0               83.4
72     EMP2073      Data Engineering         8.3  83685.0               87.4
74     EMP2075  Software Development        10.1  98224.0               83.6

    Projects_Completed
1                 11.0
6                  0.0
17                 9.0
22                12.0
25                 NaN
26                19.0
30                 6.0
31                 6.0
45                 2.0
48                 5.0
49                11.0
57                 6.0
58                 7.0
62                15.0
65                10.0
69                 1.0
72                16.0
74                13.0
                      Average_Salary  Average_Performance  Total_Projects  \
Department
 data analytics         46324.000000            73.800000             6.0
Data Analytics          56936.066667            67.176471           108.0
Data Engineering        60109.916667            72.130769            73.0
HR                      63136.300000            64.900000            47.0
IT Support              64330.500000            70.416667            30.0
Software Development    61269.840000            74.933333           190.0
Software development    79595.000000            83.000000             9.0

                      Employee_Count
Department
 data analytics                    1
Data Analytics                    17
Data Engineering                  13
HR                                10
IT Support                         7
Software Development              25
Software development               1
Highest Performance Dept: Software development
   Employee_ID            Department   Salary  Performance_Score
0      EMP2001                    HR  76776.0               57.7
7      EMP2008        Data Analytics  70881.0               67.9
12     EMP2013      Data Engineering  68546.0               51.6
13     EMP2014  Software Development  67786.0               51.7
27     EMP2028                    HR  68128.0               56.3
41     EMP2042        Data Analytics  96565.0               70.1
42     EMP2043  Software Development  82170.0               67.3
43     EMP2044                    HR  66053.0               52.6
47     EMP2048            IT Support  66074.0               54.7
52     EMP2053                    HR  64357.0               47.2
60     EMP2061  Software Development  83576.0               63.1
64     EMP2065                    HR  61142.0               52.3
66     EMP2067        Data Analytics  61196.0               65.9
67     EMP2068  Software Development  73254.0               66.0
73     EMP2074      Data Engineering  84323.0               63.5